#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/dotfiles/zsh/prezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/dotfiles/zsh/prezto/init.zsh"
fi

# Customize to your needs...
#
bindkey '^P' up-history
bindkey '^N' down-history
bindkey '^r' history-incremental-search-backward

if [[ `uname -s` == "Linux" ]]; then
  setxkbmap -option ctrl:nocaps
fi


#
# Aliases
#

source $HOME/dotfiles/zsh/alias.zsh

export TERM=screen-256color

# Check for local settings
if [[ -s "${ZDOTDIR:-$HOME}/.local.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.local.zsh"
fi
